version: '3'
services:
  node:
    restart: always
    build: .
    ports:
      - "88:3000"
    volumes:
      - ./:/app
  mongo:
    image: mongo
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
